
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_H
#define TESTSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
uint32_t TestSlave_valueRangeTest (uint8_t typeValue, void * value);
const indextable * TestSlave_scanIndexOD (uint16_t wIndex, uint32_t * errorCode, ODCallback_t **callbacks);


/* Master node data struct */
extern CO_Data TestSlave_Data;
extern uint8_t SlaveMap1;		/* Mapped at index 0x2000, subindex 0x00*/
extern uint8_t SlaveMap2;		/* Mapped at index 0x2001, subindex 0x00*/
extern uint8_t SlaveMap3;		/* Mapped at index 0x2002, subindex 0x00*/
extern uint8_t SlaveMap4;		/* Mapped at index 0x2003, subindex 0x00*/
extern uint8_t SlaveMap5;		/* Mapped at index 0x2004, subindex 0x00*/
extern uint8_t SlaveMap6;		/* Mapped at index 0x2005, subindex 0x00*/
extern uint8_t SlaveMap7;		/* Mapped at index 0x2006, subindex 0x00*/
extern uint8_t SlaveMap8;		/* Mapped at index 0x2007, subindex 0x00*/
extern uint8_t SlaveMap9;		/* Mapped at index 0x2008, subindex 0x00*/
extern uint32_t SlaveMap10;		/* Mapped at index 0x2009, subindex 0x00*/
extern uint16_t SlaveMap11;		/* Mapped at index 0x200A, subindex 0x00*/
extern INTEGER16 SlaveMap12;		/* Mapped at index 0x200B, subindex 0x00*/
extern INTEGER16 SlaveMap13;		/* Mapped at index 0x200C, subindex 0x00*/

#endif // TESTSLAVE_H
